# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: debian:buster-slim

before_script:
  - apt-get update
  - apt-get -qy install --no-install-recommends hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
