title: Ripple
theme: fastlane-hugo-theme
baseURL: http://localhost:1313

contentDir: metadata

staticDir:
  - app/src/main/res

blackfriday:
  extensions:
    - hardLineBreak

params:
  fastlaneDir: metadata
  fdroid: info.guardianproject.ripple
  github: guardianproject/ripple
  gitlab: guardianproject/ripple
  header_heading_color: "#000"
  section_headings_color: "#0091EA"

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageCode: en-US
  pt:
    languageCode: pt
